name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: gabrieloliveiranet
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: gabrieloliveiranet/minecraft-bedrock-server-editor
          dockerfile: Dockerfile
          tags: |
            gabrieloliveiranet/minecraft-bedrock-server-editor:latest
            gabrieloliveiranet/minecraft-bedrock-server-editor:1.16.40.02